#include "config.h"
#include "config_data.h" // Generated by build script

JsonDocument Config::doc;
bool Config::initialized = false;

bool Config::begin() {
  if (initialized) {
    return true;
  }

  Serial.println("Parsing embedded configuration...");

  DeserializationError error = deserializeJson(doc, CONFIG_JSON);

  if (error) {
    Serial.print("Failed to parse config JSON: ");
    Serial.println(error.c_str());
    return false;
  }

  initialized = true;
  Serial.println("Configuration loaded successfully");
  return true;
}

const char *Config::getWifiSSID() {
  const char *value = doc["wifi"]["ssid"];
  if (!value) {
    Serial.println("FATAL: Missing wifi.ssid in config");
    for (;;);
  }
  return value;
}

const char *Config::getWifiPassword() {
  const char *value = doc["wifi"]["password"];
  if (!value) {
    Serial.println("FATAL: Missing wifi.password in config");
    for (;;);
  }
  return value;
}

const char *Config::getApiUrl() {
  const char *value = doc["api"]["url"];
  if (!value) {
    Serial.println("FATAL: Missing api.url in config");
    for (;;);
  }
  return value;
}

const char *Config::getApiSecret() {
  const char *value = doc["api"]["secret"];
  if (!value) {
    Serial.println("FATAL: Missing api.secret in config");
    for (;;);
  }
  return value;
}

const char *Config::getGeoLat() {
  const char *value = doc["geo"]["lat"];
  if (!value) {
    Serial.println("FATAL: Missing geo.lat in config");
    for (;;);
  }
  return value;
}

const char *Config::getGeoLon() {
  const char *value = doc["geo"]["lon"];
  if (!value) {
    Serial.println("FATAL: Missing geo.lon in config");
    for (;;);
  }
  return value;
}
